//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control
    {
        public int ControlID { get; set; }
        public int ControlTypeID { get; set; }
        public string ControlName { get; set; }
        public int ParentControlID { get; set; }
    
        public virtual ControlType ControlType { get; set; }
    }
}
