//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlType
    {
        public ControlType()
        {
            this.Controls = new HashSet<Control>();
        }
    
        public int ControlTypeID { get; set; }
        public string ControlTypeName { get; set; }
    
        public virtual ICollection<Control> Controls { get; set; }
    }
}
