//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthentication
    {
        public int UserAuthenticationID { get; set; }
        public int UserAuthenticationTypeID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserEmail { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserAuthenticationType UserAuthenticationType { get; set; }
    }
}
