//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthenticationType
    {
        public UserAuthenticationType()
        {
            this.UserAuthentications = new HashSet<UserAuthentication>();
        }
    
        public int UserAuthenticationTypeID { get; set; }
        public string UserAuthenticationTypeDescription { get; set; }
    
        public virtual ICollection<UserAuthentication> UserAuthentications { get; set; }
    }
}
